## Bài 11: Bài tập áp dụng

In [ ]:
#BT11
import torch

X = torch.arange(24)
print("X ban đầu:")
print(X)

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("\nReshape 4 x 6:")
print(X_4x6)
print("\nReshape 2 x 12:")
print(X_2x12)
print("\nReshape 2 x 3 x 4:")
print(X_2x3x4)


X ban đầu:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Reshape 4 x 6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape 2 x 12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape 2 x 3 x 4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [16]:
import torch

A = torch.randn(3, 4)
B = torch.randn(3, 4)
print("A:")
print(A)
print("B:")
print(B)

print("\nA + B:")
print(A + B)
print("\nA * B (element-wise):")
print(A * B)
print("\nA / B:")
print(A / B)
print("\nMean theo cột (dim=0):")
print(torch.mean(A, dim=0))
print("\nStd theo cột (dim=0):")
print(torch.std(A, dim=0))


A:
tensor([[-0.9740,  1.2610, -1.1296, -1.3212],
        [-0.5016, -0.4413, -2.0748,  1.4175],
        [ 1.0093,  0.1953, -1.3764, -1.0361]])
B:
tensor([[ 0.1549, -0.9514, -1.4261,  0.3507],
        [-0.9024, -0.6517,  0.3229, -0.8498],
        [ 1.0405, -1.2257, -1.8195,  0.3582]])

A + B:
tensor([[-0.8190,  0.3096, -2.5557, -0.9705],
        [-1.4040, -1.0930, -1.7518,  0.5677],
        [ 2.0498, -1.0303, -3.1959, -0.6779]])

A * B (element-wise):
tensor([[-0.1509, -1.1997,  1.6109, -0.4634],
        [ 0.4527,  0.2876, -0.6700, -1.2045],
        [ 1.0502, -0.2394,  2.5044, -0.3711]])

A / B:
tensor([[-6.2861, -1.3254,  0.7921, -3.7674],
        [ 0.5559,  0.6773, -6.4249, -1.6681],
        [ 0.9699, -0.1594,  0.7565, -2.8926]])

Mean theo cột (dim=0):
tensor([-0.1554,  0.3383, -1.5269, -0.3133])

Std theo cột (dim=0):
tensor([1.0359, 0.8601, 0.4902, 1.5056])


In [17]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

print("x =", x)
print("y =", y)
print("dy/dx (autograd) =", x.grad)

manual_grad = 4 * 2 + 5  # y' = 4x + 5
print("dy/dx (tính thủ công tại x=2) =", manual_grad)


x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
dy/dx (autograd) = tensor(13.)
dy/dx (tính thủ công tại x=2) = 13


In [18]:
import numpy as np
import torch

polynomial = np.poly1d([2, -3, 5])   # y = 2x^2 - 3x + 5
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(3000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients (kỳ vọng gần [2, -3, 5]):")
print(w)


Initial coefficients:
tensor([[-0.2952],
        [-0.1180],
        [-0.5429]], requires_grad=True)
Learned coefficients (kỳ vọng gần [2, -3, 5]):
tensor([[ 2.0128],
        [-2.9723],
        [ 4.3330]], requires_grad=True)
