In [1]:
#Bài 2 — Tạo các Tensor thường dùng
import torch
a= torch.rand(3,4)
b= torch.randn(3,4)
c= torch.zeros(2,3)
d= torch.ones(2,3)
e= torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.0243, 0.3380, 0.3134, 0.5868],
        [0.4604, 0.1667, 0.9303, 0.6670],
        [0.3218, 0.1692, 0.4114, 0.7017]])
tensor([[-0.3402, -0.7360, -2.1009, -1.6179],
        [ 1.2396,  0.3965, -0.1347,  0.0648],
        [-1.3151,  0.2621,  0.0923, -2.7580]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
