In [1]:
#Bài 4 — Slicing và Indexing
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.9570, -1.7506, -1.1285,  1.0051, -0.1555],
         [-0.8185,  0.0317,  1.9157, -1.5178,  1.0541],
         [-0.0489, -0.7029,  0.1960, -1.5113, -0.0414],
         [ 0.4873, -0.6337, -0.3958, -1.1776, -0.6348]],

        [[ 0.4994,  0.6601,  1.8955,  0.6810, -0.0978],
         [ 0.5553,  2.0743, -0.2822, -0.3579,  2.1991],
         [-0.4472,  0.5160, -0.5125,  0.5109,  0.5290],
         [ 0.3476,  1.1014, -0.0043,  1.6355, -0.0528]],

        [[-1.8606, -0.1080,  2.2350, -0.3590,  1.0604],
         [-0.8053,  0.4893,  0.7345, -0.7757, -0.3370],
         [-0.9371,  0.7511, -0.4814,  0.5783, -1.1753],
         [-0.3600,  0.2580, -0.9965, -1.6790, -1.4640]]])

Tensor a[1]:
tensor([[ 0.4994,  0.6601,  1.8955,  0.6810, -0.0978],
        [ 0.5553,  2.0743, -0.2822, -0.3579,  2.1991],
        [-0.4472,  0.5160, -0.5125,  0.5109,  0.5290],
        [ 0.3476,  1.1014, -0.0043,  1.6355, -0.0528]])

Tensor a[1:, 2:4]:
tensor([[[-0.4472,  0.5160, -0.5125,  0.5109,  0.5