In [1]:
#Bài 5 — Reshape và Flatten
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.3345, -0.4390, -1.1391,  0.6489],
        [ 0.1289,  0.1493,  1.4375,  1.5146],
        [ 0.7546,  0.2961, -0.9394, -2.2052]])

Flatten:
tensor([-0.3345, -0.4390, -1.1391,  0.6489,  0.1289,  0.1493,  1.4375,  1.5146,
         0.7546,  0.2961, -0.9394, -2.2052])

Reshape to 3 x 2 x 2:
tensor([[[-0.3345, -0.4390],
         [-1.1391,  0.6489]],

        [[ 0.1289,  0.1493],
         [ 1.4375,  1.5146]],

        [[ 0.7546,  0.2961],
         [-0.9394, -2.2052]]])
