In [1]:
#Bài 6 — Phép toán và nhân ma trận
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)


print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 3.3600,  0.2499, -1.9540],
        [-0.4586, -2.1873, -1.2711]])
b:
tensor([[ 0.2500,  0.3397, -0.9190],
        [-0.0106, -0.0283, -1.4693]])

a + b:
tensor([[ 3.6100,  0.5896, -2.8730],
        [-0.4692, -2.2156, -2.7404]])

a / b:
tensor([[13.4419,  0.7357,  2.1263],
        [43.2954, 77.3458,  0.8651]])

a^2:
tensor([[11.2899,  0.0625,  3.8183],
        [ 0.2104,  4.7844,  1.6157]])

Matrix multiplication:
tensor([[2.7206, 2.8284],
        [0.3105, 1.9344]])
