In [1]:
#Bài 7 — Các hàm thống kê
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))


tensor([[ 1.3538, -0.1638,  0.6258,  1.3795],
        [-1.5845,  0.4420,  1.6883,  0.6559],
        [-0.2557,  1.6346, -0.3425, -0.3656]])

Mean:
tensor([-0.1621,  0.6376,  0.6572,  0.5566])

Standard deviation:
tensor([1.4714, 0.9150, 1.0158, 0.8768])

Cumulative sum:
tensor([[ 1.3538, -0.1638,  0.6258,  1.3795],
        [-0.2306,  0.2782,  2.3141,  2.0355],
        [-0.4864,  1.9128,  1.9717,  1.6699]])
